defaults:
  - model: base
  - train: train
  - embedding: embedding
  - data: data
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

train_dataset_dir: /root/MassiveKBV2

hydra:  
  output_subdir: null  
  run:  
    dir: .

wandb:
  entity: prototype
  project: RNovA
  name: base-epsilon
